#include "includes/io.hpp"


namespace Quest{
    QUEST_CREATE_LOCAL_FLAG(IO, READ,   1);
    QUEST_CREATE_LOCAL_FLAG(IO, WRITE,  2);
    QUEST_CREATE_LOCAL_FLAG(IO, APPEND, 3);
    QUEST_CREATE_LOCAL_FLAG(IO, IGNORE_VARIABLES_ERROR, 4); 
    QUEST_CREATE_LOCAL_FLAG(IO, SKIP_TIMER, 5);
    QUEST_CREATE_LOCAL_FLAG(IO, MESH_ONLY, 6);
    QUEST_CREATE_LOCAL_FLAG(IO, SCIENTIFIC_PRECISION, 7);
}