/*--------------------------
定义了QuestCAE的变量
--------------------------*/

#ifndef QUEST_VARIABLES_HPP
#define QUEST_VARIABLES_HPP

// 系统头文件
#include <string>
#include <iostream>

// 项目头文件
#include "includes/define.hpp"
#include "container/variable.hpp"
#include "includes/quest_components.hpp"
#include "includes/ublas_interface.hpp"
#include "container/array_1d.hpp"
#include "container/global_pointers_vector.hpp"
#include "container/periodic_variable_container.hpp"
#include "utilities/table_stream_utility.hpp"
#include "utilities/adjoint_extensions.hpp"

#undef QUEST_EXPORT_MACRO
#define QUEST_EXPORT_MACRO QUEST_API

namespace Quest{

    QUEST_DEFINE_VARIABLE(bool, IS_RESTARTED)
    QUEST_DEFINE_VARIABLE(bool, COMPUTE_DYNAMIC_TANGENT)
    QUEST_DEFINE_VARIABLE(bool, COMPUTE_LUMPED_MASS_MATRIX)


    QUEST_DEFINE_VARIABLE(int, DOMAIN_SIZE)
    QUEST_DEFINE_VARIABLE(int, SPACE_DIMENSION)


    QUEST_DEFINE_VARIABLE(int, LOAD_RESTART)
    QUEST_DEFINE_VARIABLE(int, TIME_STEP)
    QUEST_DEFINE_VARIABLE(int, RIGID_BODY_ID)


    QUEST_DEFINE_VARIABLE(int, FIRST_TIEM_STEP)
    QUEST_DEFINE_VARIABLE(int, QUASI_STATIC_ANALYSIS)


    QUEST_DEFINE_VARIABLE(int, NL_INERATION_NUMBER)  
    QUEST_DEFINE_VARIABLE(int, PERIODIC_PAIR_INDEX)
    QUEST_DEFINE_VARIABLE(int, STATIONARY)
    QUEST_DEFINE_VARIABLE(int, ACTIVATION_LEVEL)
    QUEST_DEFINE_VARIABLE(int, PARTITION_MASK)


    QUEST_DEFINE_VARIABLE(int, SCALE)


    QUEST_DEFINE_VARIABLE(int, REFINEMENT_LEVEL)
    QUEST_DEFINE_VARIABLE(int, STEP)
    QUEST_DEFINE_VARIABLE(int, PRINTED_STEP)
    QUEST_DEFINE_VARIABLE(int, PRINTED_RESTART_STEP)
    QUEST_DEFINE_VARIABLE(int, RUNGE_KUTTA_STEP)


    QUEST_DEFINE_VARIABLE(double, TIME)  // 求解事件
    QUEST_DEFINE_VARIABLE(double, START_TIME)
    QUEST_DEFINE_VARIABLE(double, END_TIME)
    QUEST_DEFINE_VARIABLE(double, DELTA_TIME)  // 时间步增量
    QUEST_DEFINE_VARIABLE(double, PREVIOUS_DELTA_TIME)
    QUEST_DEFINE_VARIABLE(double, INTERVAL_END_TIME)


    QUEST_DEFINE_VARIABLE(double, RESIDUAL_NORM)
    QUEST_DEFINE_VARIABLE(double, CONVERGENCE_RATIO)
    QUEST_DEFINE_VARIABLE(double, BUILD_SCALE_FACTOR)
    QUEST_DEFINE_VARIABLE(double, CONSTRAINT_SCALE_FACTOR)
    QUEST_DEFINE_VARIABLE(double, AUXILIAR_CONSTRAINT_SCALE_FACTOR)


    QUEST_DEFINE_VARIABLE(double, TEMPERATURE)
    QUEST_DEFINE_VARIABLE(double, PRESSURE)


    QUEST_DEFINE_VARIABLE( double, NEGATIVE_FACE_PRESSURE )
    QUEST_DEFINE_VARIABLE( double, POSITIVE_FACE_PRESSURE )
    QUEST_DEFINE_VARIABLE( double, FACE_HEAT_FLUX )

    QUEST_DEFINE_VARIABLE( double, DENSITY )
    QUEST_DEFINE_VARIABLE( double, YOUNG_MODULUS )
    QUEST_DEFINE_VARIABLE( double, POISSON_RATIO )
    QUEST_DEFINE_VARIABLE( double, SHEAR_MODULUS_GAMMA12)
    QUEST_DEFINE_VARIABLE( double, SHEAR_MODULUS_GAMMA12_2)
    QUEST_DEFINE_VARIABLE( double, SHEAR_MODULUS_GAMMA12_3)
    QUEST_DEFINE_VARIABLE( double, SHEAR_MODULUS_GAMMA12_4)

    QUEST_DEFINE_VARIABLE( double, THICKNESS )
    QUEST_DEFINE_VARIABLE( double, EQUIVALENT_YOUNG_MODULUS )

    QUEST_DEFINE_VARIABLE( double, NODAL_H )

    QUEST_DEFINE_VARIABLE( double, KINETIC_ENERGY )
    QUEST_DEFINE_VARIABLE( double, INTERNAL_ENERGY )
    QUEST_DEFINE_VARIABLE( double, STRAIN_ENERGY )
    QUEST_DEFINE_VARIABLE( double, EXTERNAL_ENERGY )
    QUEST_DEFINE_VARIABLE( double, TOTAL_ENERGY )

    QUEST_DEFINE_VARIABLE( double, VOLUMETRIC_STRAIN )

    QUEST_DEFINE_VARIABLE( double, THERMAL_EXPANSION_COEFFICIENT )
    QUEST_DEFINE_VARIABLE( double, STABILIZATION_FACTOR )
    QUEST_DEFINE_VARIABLE( double, DETERMINANT_F )

    QUEST_DEFINE_VARIABLE( double, PENALTY_COEFFICIENT )
    QUEST_DEFINE_VARIABLE( double, GRADIENT_PENALTY_COEFFICIENT )

    QUEST_DEFINE_VARIABLE( double, TIME_INTEGRATION_THETA )

    // for geometrical application
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( CHARACTERISTIC_GEOMETRY_LENGTH )

    //scheme info :: pass to elements
    QUEST_DEFINE_VARIABLE( double, NEWMARK_BETA )
    QUEST_DEFINE_VARIABLE( double, NEWMARK_GAMMA )
    QUEST_DEFINE_VARIABLE( double, BOSSAK_ALPHA )
    QUEST_DEFINE_VARIABLE( double, EQUILIBRIUM_POINT )

    // Lagrange multiplier for general purpose
    QUEST_DEFINE_VARIABLE( double,            SCALAR_LAGRANGE_MULTIPLIER )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( VECTOR_LAGRANGE_MULTIPLIER )

    //for Structural application
    QUEST_DEFINE_VARIABLE( double, FRICTION_COEFFICIENT )
    QUEST_DEFINE_VARIABLE( double, LAMBDA )
    QUEST_DEFINE_VARIABLE( double, MIU )
    QUEST_DEFINE_VARIABLE( double, SCALE_FACTOR )
    QUEST_DEFINE_VARIABLE( double, NORMAL_CONTACT_STRESS )
    QUEST_DEFINE_VARIABLE( double, TANGENTIAL_CONTACT_STRESS )

    QUEST_DEFINE_VARIABLE( int,    PARTITION_INDEX )
    QUEST_DEFINE_VARIABLE( double, TEMPERATURE_OLD_IT )
    QUEST_DEFINE_VARIABLE( double, VISCOSITY )
    QUEST_DEFINE_VARIABLE( double, ERROR_RATIO )
    QUEST_DEFINE_VARIABLE( double, ENERGY_NORM_OVERALL )
    QUEST_DEFINE_VARIABLE( double, ERROR_OVERALL )
    QUEST_DEFINE_VARIABLE( double, RHS_WATER )
    QUEST_DEFINE_VARIABLE( double, RHS_AIR )
    QUEST_DEFINE_VARIABLE( double, WEIGHT_FATHER_NODES )
    QUEST_DEFINE_VARIABLE( double, INITIAL_PENALTY )
    QUEST_DEFINE_VARIABLE( double, DP_EPSILON )
    QUEST_DEFINE_VARIABLE( double, DP_ALPHA1 )
    QUEST_DEFINE_VARIABLE( double, DP_K )
    QUEST_DEFINE_VARIABLE( double, INTERNAL_FRICTION_ANGLE )
    QUEST_DEFINE_VARIABLE( double, K0 )
    QUEST_DEFINE_VARIABLE( double, NODAL_VOLUME )

    QUEST_DEFINE_VARIABLE( double, WATER_PRESSURE )
    QUEST_DEFINE_VARIABLE( double, REACTION_WATER_PRESSURE )

    QUEST_DEFINE_VARIABLE( double, WATER_PRESSURE_ACCELERATION )

    QUEST_DEFINE_VARIABLE( double, AIR_PRESSURE )
    QUEST_DEFINE_VARIABLE( double, REACTION_AIR_PRESSURE )
    QUEST_DEFINE_VARIABLE( double, FLAG_VARIABLE )
    QUEST_DEFINE_VARIABLE( double, DISTANCE )
    QUEST_DEFINE_VARIABLE( double, AUX_DISTANCE )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DISTANCE_GRADIENT )

    QUEST_DEFINE_VARIABLE( double, LAGRANGE_AIR_PRESSURE )
    QUEST_DEFINE_VARIABLE( double, LAGRANGE_WATER_PRESSURE )
    QUEST_DEFINE_VARIABLE( double, LAGRANGE_TEMPERATURE )

    //MeshMovingApplication
    QUEST_DEFINE_VARIABLE( double, AUX_MESH_VAR )

    //for MultiScale application
    QUEST_DEFINE_VARIABLE( Vector, INITIAL_STRAIN )
    QUEST_DEFINE_VARIABLE( double, COEFFICIENT_THERMAL_EXPANSION )
    QUEST_DEFINE_VARIABLE( double, CHARACTERISTIC_LENGTH_MULTIPLIER )

    //Adjoint
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ADJOINT_VECTOR_1 )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ADJOINT_VECTOR_2 )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ADJOINT_VECTOR_3 )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( AUX_ADJOINT_VECTOR_1 )
    QUEST_DEFINE_VARIABLE(double, ADJOINT_SCALAR_1 )
    QUEST_DEFINE_VARIABLE(double, SCALAR_SENSITIVITY )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( SHAPE_SENSITIVITY )
    QUEST_DEFINE_VARIABLE(double, NORMAL_SENSITIVITY )
    QUEST_DEFINE_VARIABLE(double, NUMBER_OF_NEIGHBOUR_ELEMENTS )
    QUEST_DEFINE_VARIABLE(bool, UPDATE_SENSITIVITIES )
    QUEST_DEFINE_VARIABLE(AdjointExtensions::Pointer, ADJOINT_EXTENSIONS )
    QUEST_DEFINE_VARIABLE(Matrix, NORMAL_SHAPE_DERIVATIVE )

    // For MeshingApplication
    QUEST_DEFINE_VARIABLE( double, NODAL_ERROR )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( NODAL_ERROR_COMPONENTS )
    QUEST_DEFINE_VARIABLE( double, ELEMENT_ERROR )
    QUEST_DEFINE_VARIABLE( double, ELEMENT_H )
    QUEST_DEFINE_VARIABLE( Vector, RECOVERED_STRESS )
    QUEST_DEFINE_VARIABLE( double, ERROR_INTEGRATION_POINT )
    QUEST_DEFINE_VARIABLE( double, CONTACT_PRESSURE )

    //for PFEM fluids application:
    QUEST_DEFINE_VARIABLE( double, NODAL_AREA )

    QUEST_DEFINE_VARIABLE( double, BULK_MODULUS )
    QUEST_DEFINE_VARIABLE( double, SATURATION )
    QUEST_DEFINE_VARIABLE( double, DENSITY_WATER )
    QUEST_DEFINE_VARIABLE( double, VISCOSITY_WATER )
    QUEST_DEFINE_VARIABLE( double, DENSITY_AIR )
    QUEST_DEFINE_VARIABLE( double, VISCOSITY_AIR )
    QUEST_DEFINE_VARIABLE( double, POROSITY )
    QUEST_DEFINE_VARIABLE( double, DIAMETER )
    QUEST_DEFINE_VARIABLE( double, LIN_DARCY_COEF )
    QUEST_DEFINE_VARIABLE( double, NONLIN_DARCY_COEF )

    QUEST_DEFINE_VARIABLE( double, AIR_ENTRY_VALUE )
    QUEST_DEFINE_VARIABLE( double, FIRST_SATURATION_PARAM )
    QUEST_DEFINE_VARIABLE( double, SECOND_SATURATION_PARAM )
    QUEST_DEFINE_VARIABLE( double, PERMEABILITY_WATER )
    QUEST_DEFINE_VARIABLE( double, PERMEABILITY_AIR )
    QUEST_DEFINE_VARIABLE( double, BULK_AIR )

    QUEST_DEFINE_VARIABLE( double, TEMP_CONV_PROJ )
    QUEST_DEFINE_VARIABLE( double, CONVECTION_COEFFICIENT )

    QUEST_DEFINE_VARIABLE( double, SOUND_VELOCITY )
    QUEST_DEFINE_VARIABLE( double, AIR_SOUND_VELOCITY )
    QUEST_DEFINE_VARIABLE( double, WATER_SOUND_VELOCITY )
    QUEST_DEFINE_VARIABLE( double, NODAL_MASS )
    QUEST_DEFINE_SYMMETRIC_3D_TENSOR_VARIABLE_WITH_COMPONENTS( NODAL_INERTIA_TENSOR )
    QUEST_DEFINE_VARIABLE( double, AUX_INDEX )
    QUEST_DEFINE_VARIABLE( double, VELOCITY_PERIOD )
    QUEST_DEFINE_VARIABLE( double, ANGULAR_VELOCITY_PERIOD )
    QUEST_DEFINE_VARIABLE( std::string, IDENTIFIER )

    //for Other applications:
    QUEST_DEFINE_VARIABLE( double, ARRHENIUS )
    QUEST_DEFINE_VARIABLE( double, ARRHENIUSAUX )
    QUEST_DEFINE_VARIABLE( double, ARRHENIUSAUX_ )
    QUEST_DEFINE_VARIABLE( double, PRESSUREAUX )
    QUEST_DEFINE_VARIABLE( double, NODAL_MAUX )
    QUEST_DEFINE_VARIABLE( double, NODAL_PAUX )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( NODAL_VAUX )
    QUEST_DEFINE_VARIABLE( double, HEAT_FLUX )
    QUEST_DEFINE_VARIABLE( double, REACTION_FLUX )
    QUEST_DEFINE_VARIABLE( double, TC )
    QUEST_DEFINE_VARIABLE( double, CONDUCTIVITY )
    QUEST_DEFINE_VARIABLE( double, SPECIFIC_HEAT )
    QUEST_DEFINE_VARIABLE( double, MATERIAL_VARIABLE )
    QUEST_DEFINE_VARIABLE( double, FUEL )
    QUEST_DEFINE_VARIABLE( double, YO )
    QUEST_DEFINE_VARIABLE( double, YF )
    QUEST_DEFINE_VARIABLE( double, YI )
    QUEST_DEFINE_VARIABLE( double, Y1 )
    QUEST_DEFINE_VARIABLE( double, Y2 )
    QUEST_DEFINE_VARIABLE( double, YP )

    QUEST_DEFINE_VARIABLE( double, ABSORPTION_COEFFICIENT )
    QUEST_DEFINE_VARIABLE( double, STEFAN_BOLTZMANN_CONSTANT )

    QUEST_DEFINE_VARIABLE( double, EXTERNAL_PRESSURE )

    QUEST_DEFINE_VARIABLE( double, EMISSIVITY )
    QUEST_DEFINE_VARIABLE( double, ENTHALPY )
    QUEST_DEFINE_VARIABLE( double, MIXTURE_FRACTION )


    QUEST_DEFINE_VARIABLE( double, YCH4 )
    QUEST_DEFINE_VARIABLE( double, YO2 )
    QUEST_DEFINE_VARIABLE( double, YCO2 )
    QUEST_DEFINE_VARIABLE( double, YH2O )
    QUEST_DEFINE_VARIABLE( double, YN2 )

    QUEST_DEFINE_VARIABLE( double, WET_VOLUME )
    QUEST_DEFINE_VARIABLE( double, CUTTED_AREA )
    QUEST_DEFINE_VARIABLE( double, NET_INPUT_MATERIAL )

    QUEST_DEFINE_VARIABLE( double, INCIDENT_RADIATION_FUNCTION )

    QUEST_DEFINE_VARIABLE( double, SWITCH_TEMPERATURE )
    QUEST_DEFINE_VARIABLE( double, NODAL_SWITCH )

    //for Xfem application:
    QUEST_DEFINE_VARIABLE( double, CRACK_OPENING )
    QUEST_DEFINE_VARIABLE( double, CRACK_TRANSLATION )

    //for Level Set application:
    QUEST_DEFINE_VARIABLE( double, MIN_DT )
    QUEST_DEFINE_VARIABLE( double, MAX_DT )
    QUEST_DEFINE_VARIABLE( double, VEL_ART_VISC )
    QUEST_DEFINE_VARIABLE( double, PR_ART_VISC )
    QUEST_DEFINE_VARIABLE( double, LIMITER_COEFFICIENT )

    //for Vulcan application
    QUEST_DEFINE_VARIABLE( double, LATENT_HEAT )
    QUEST_DEFINE_VARIABLE( double, AMBIENT_TEMPERATURE )

    //vectors

    //for General kratos application:
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ROTATION )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DELTA_ROTATION )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( REACTION_MOMENT )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ANGULAR_VELOCITY )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ANGULAR_ACCELERATION )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( VELOCITY_LAPLACIAN )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( VELOCITY_LAPLACIAN_RATE )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( VELOCITY_COMPONENT_GRADIENT )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( VELOCITY_X_GRADIENT )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( VELOCITY_Y_GRADIENT )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( VELOCITY_Z_GRADIENT )

    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( REACTION )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( VELOCITY )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ACCELERATION )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( STEP_ROTATION )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( STEP_DISPLACEMENT )

    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( VOLUME_ACCELERATION )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( FORCE )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( TORQUE )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( MOMENT )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( FACE_LOAD )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( NORMAL )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( TANGENT_XI )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( TANGENT_ETA )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( LOCAL_TANGENT )
    QUEST_DEFINE_VARIABLE( Matrix, LOCAL_TANGENT_MATRIX )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( BODY_FORCE )

    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( FORCE_RESIDUAL )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( MOMENT_RESIDUAL )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( INTERNAL_FORCE )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( EXTERNAL_FORCE )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( CONTACT_FORCE )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( CONTACT_NORMAL )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( TEMPERATURE_GRADIENT )

    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( LINEAR_MOMENTUM )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ANGULAR_MOMENTUM )

    QUEST_DEFINE_VARIABLE( Vector, EXTERNAL_FORCES_VECTOR )
    QUEST_DEFINE_VARIABLE( Vector, INTERNAL_FORCES_VECTOR )
    QUEST_DEFINE_VARIABLE( Vector, CONTACT_FORCES_VECTOR )

    QUEST_DEFINE_VARIABLE( Vector, CAUCHY_STRESS_VECTOR )
    QUEST_DEFINE_VARIABLE( Vector, PK2_STRESS_VECTOR )

    QUEST_DEFINE_VARIABLE( Vector, RESIDUAL_VECTOR )

    QUEST_DEFINE_VARIABLE( Vector, MARKER_LABELS )
    QUEST_DEFINE_VARIABLE( Vector, MARKER_MESHES )

    QUEST_DEFINE_VARIABLE( Vector, CONSTRAINT_LABELS )
    QUEST_DEFINE_VARIABLE( Vector, CONSTRAINT_MESHES )

    QUEST_DEFINE_VARIABLE( Vector, LOAD_LABELS )
    QUEST_DEFINE_VARIABLE( Vector, LOAD_MESHES )

    QUEST_DEFINE_VARIABLE( Vector, SHAPE_FUNCTIONS_VECTOR )

    //for Structural application:
    QUEST_DEFINE_VARIABLE(  int, NUMBER_OF_CYCLES )

    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( MOMENTUM )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( LAGRANGE_DISPLACEMENT )

    QUEST_DEFINE_VARIABLE( Vector, ELEMENTAL_DISTANCES )
    QUEST_DEFINE_VARIABLE( Vector, ELEMENTAL_EDGE_DISTANCES )
    QUEST_DEFINE_VARIABLE( Vector, ELEMENTAL_EDGE_DISTANCES_EXTRAPOLATED )
    QUEST_DEFINE_VARIABLE( Vector, MATERIAL_PARAMETERS )
    QUEST_DEFINE_VARIABLE( Vector, INTERNAL_VARIABLES )
    QUEST_DEFINE_VARIABLE( Vector, INSITU_STRESS )

    QUEST_DEFINE_VARIABLE( Vector, PENALTY )
    QUEST_DEFINE_VARIABLE( Vector, NORMAL_STRESS )
    QUEST_DEFINE_VARIABLE( Vector, TANGENTIAL_STRESS )
    QUEST_DEFINE_VARIABLE( Vector, STRESSES )
    QUEST_DEFINE_VARIABLE( Vector, STRAIN )

    QUEST_DEFINE_VARIABLE( DenseVector<int>, NEIGHBOURS_INDICES )

    //ALE Application
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DETERMINANT )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ELEMENTSHAPE )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( MESH_VELOCITY )

    //for PFEM fluids application:
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( GRAVITY )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( NORMAL_TO_WALL )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( STRUCTURE_VELOCITY )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DRAG_FORCE )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( EMBEDDED_VELOCITY )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( FRACT_VEL )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ROTATION_CENTER )

    //for Other applications:
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( SEEPAGE_DRAG )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( MASS )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( RHS )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( FORCE_CM )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( MOMENTUM_CM )

    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DIRECTION )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( Y )

    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( LOCAL_AXIS_1 )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( LOCAL_AXIS_2 )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( LOCAL_AXIS_3 )


    QUEST_DEFINE_VARIABLE( Vector, BDF_COEFFICIENTS )

    //for Vulcan application
    QUEST_DEFINE_VARIABLE( Vector, ENRICHED_PRESSURES )

    //matrices

    //for General kratos application:
    QUEST_DEFINE_VARIABLE( Matrix, GREEN_LAGRANGE_STRAIN_TENSOR )
    QUEST_DEFINE_VARIABLE( Matrix, PK2_STRESS_TENSOR )
    QUEST_DEFINE_VARIABLE( Matrix, CAUCHY_STRESS_TENSOR )
    QUEST_DEFINE_VARIABLE( Matrix, LOCAL_INERTIA_TENSOR )
    QUEST_DEFINE_VARIABLE( Matrix, LOCAL_AXES_MATRIX )
    QUEST_DEFINE_VARIABLE( Matrix, LOCAL_CONSTITUTIVE_MATRIX )
    QUEST_DEFINE_VARIABLE( Matrix, CONSTITUTIVE_MATRIX )
    QUEST_DEFINE_VARIABLE( Matrix, DEFORMATION_GRADIENT )
    QUEST_DEFINE_VARIABLE( Matrix, MATERIAL_STIFFNESS_MATRIX )
    QUEST_DEFINE_VARIABLE( Matrix, GEOMETRIC_STIFFNESS_MATRIX )
    QUEST_DEFINE_VARIABLE( Matrix, SHAPE_FUNCTIONS_GRADIENT_MATRIX)
    QUEST_DEFINE_VARIABLE( Vector, DETERMINANTS_OF_JACOBIAN_PARENT)
    QUEST_DEFINE_VARIABLE( Quaternion<double>, ORIENTATION )

    //for Structural application:
    QUEST_DEFINE_VARIABLE( Matrix, INERTIA )

    QUEST_DEFINE_VARIABLE( PeriodicVariablesContainer, PERIODIC_VARIABLES )

    // Variables that should be moved to applications (but have too many dependencies)
    QUEST_DEFINE_VARIABLE(int, FRACTIONAL_STEP)
    QUEST_DEFINE_VARIABLE(double, EQ_STRAIN_RATE)
    QUEST_DEFINE_VARIABLE(double, POWER_LAW_N)
    QUEST_DEFINE_VARIABLE(double, POWER_LAW_K)
    QUEST_DEFINE_VARIABLE(double, YIELD_STRESS)
    QUEST_DEFINE_VARIABLE(double, MU)
    QUEST_DEFINE_VARIABLE(double, TAU)

    QUEST_DEFINE_VARIABLE(double, SEARCH_RADIUS )

    QUEST_DEFINE_VARIABLE(double, INTEGRATION_WEIGHT )
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS( INTEGRATION_COORDINATES )
    QUEST_DEFINE_VARIABLE(TableStreamUtility::Pointer, TABLE_UTILITY )

    //for Geometry Variables
    QUEST_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PARAMETER_2D_COORDINATES)

    // Variational redistance
    QUEST_DEFINE_VARIABLE(double, VARIATIONAL_REDISTANCE_COEFFICIENT_FIRST)
    QUEST_DEFINE_VARIABLE(double, VARIATIONAL_REDISTANCE_COEFFICIENT_SECOND)

} // namespace Quest

#undef QUEST_EXPORT_MACRO
#define QUEST_EXPORT_MACRO QUEST_NO_EXPORT

#endif //QUEST_VARIABLES_HPP